export enum ORDER_PROCESS_STATUS_ENUM {
    ORDERED = "ORDERED",
    DELIVERED = "DELIVERED",
    RETURNED = "RETURNED"
}

export enum PAYMENT_STATUS_ENUM {
    PAID = "PAID",
    REFUNDED = "REFUNDED",
    PENDING = "PENDING"
}

export enum ORDER_STATUS_ENUM {
    COMPLETED = "COMPLETED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    PENDING = "PENDING"
}